import 'package:ESPP_Rewards_App_Portador/widgets/custom_appBar.dart';
import 'package:flutter/material.dart';

class TermsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBard.getAppBar(title: 'Termos de Uso'),
      body: Container(
          color: Color.fromRGBO(108, 201, 229, 0.5),
          child: SingleChildScrollView(
            padding: EdgeInsets.all(10),
            child: Text(
              'A EDENRED SOLUÇÕES DE PAGAMENTO HYLA S.A., CNPJ 59158642/0001-66, sediada à Alameda Tocantins, 350,'
              '15 andar, Alphaville'
              'Industrial, Barueri – SP, CEP 06455-020 (“EDENRED SOLUÇÕES DE PAGAMENTO”) estabelece neste Termo de'
              'Uso e Política de Privacidade'
              '(“TERMO”) as condições para utilização do Site de propriedade da EDENRED SOLUÇÕES DE PAGAMENTO'
              '(“Site”), de forma a esclarecer as'
              'obrigações e responsabilidades de seus usuários.\n\n'
              'Leia atentamente o seguinte TERMO, pois ele se aplica ao seu acesso e forma de uso das informações,'
              'incluindo aquelas relacionadas'
              'à privacidade e proteção de seus dados pessoais, materiais e itens/funções contidas neste Site e em'
              'suas páginas.'
              '\n\n\n'
              '1. DEFINIÇÕES\n'
              '\n1.1. Para os fins deste TERMO, consideram-se:'
              '\ni) Endereço de Protocolo de Internet (Endereço IP): o código atribuído a um Terminal de uma rede'
              'para permitir sua'
              'identificação, definido segundo parâmetros internacionais.'
              '\nii) Internet: o sistema constituído do conjunto de protocolos lógicos, estruturado em escala'
              'mundial para uso público e'
              'irrestrito, com a finalidade de possibilitar a comunicação de dados entre terminais por meio de'
              'diferentes redes.'
              '\niii) Senha: conjunto de caracteres que são constituídos por números, com a finalidade de'
              'verificar a identidade do Usuário'
              'para acesso ao Portal de Portador e na Central de Atendimento.'
              '\niv) Sites: sites da EDENRED SOLUÇÕES DE PAGAMENTO por meio dos quais os Usuários acessam os'
              'serviços e conteúdos'
              'disponibilizados pela EDENRED SOLUÇÕES DE PAGAMENTO.'
              '\nv) Terminais: computadores, notebooks, netbooks, smartphones, tablets, palm tops e quaisquer'
              'outros dispositivos que se'
              'conectem a Internet.'
              '\nvi) Usuários: todas as pessoas físicas que utilizarão os Sites, maiores de 18 (dezoito) anos ou'
              'emancipadas e totalmente'
              'capazes de praticar os atos da vida civil ou os absolutamente ou relativamente incapazes devidamente'
              'representados ou assistidos.'
              '\n1.2. Este TERMO deverá ser regido e interpretado de acordo com os seguintes princípios:'
              '\ni) os cabeçalhos e títulos servem apenas para conveniência de referência e não limitarão ou'
              'afetarão o significado das'
              'cláusulas, parágrafos ou itens aos quais se aplicam;'
              '\nii) os termos “inclusive”, “incluindo” e outros termos semelhantes serão interpretados como se'
              'estivessem acompanhados da'
              'frase “a título meramente exemplificativo” e “sem limitação”;'
              '\niii) sempre que exigido pelo contexto, as definições contidas neste TERMO serão aplicadas tanto'
              'no singular quanto no plural e'
              'o gênero masculino incluirá o feminino e vice-versa, sem alteração de significado;'
              '\niv) referências a qualquer documento ou outros instrumentos incluem todas as suas alterações,'
              'substituições e consolidações e'
              'respectivas complementações, salvo se expressamente disposto de forma diferente neste TERMO;'
              '\n\n2. DO OBJETO\n'
              '\n'
              '2.1. Este Termo de Uso apresenta as condições gerais aplicáveis ao uso dos serviços oferecidos pela'
              'EDENRED SOLUÇÕES DE PAGAMENTO'
              'por meio do(s) seu(s) Site(s).'
              '\n2.2. Os Sites possuem somente áreas de conteúdo e/ou serviços restritos.'
              '\n\n3. DO SITE\n'
              '\n3.1 O Site de propriedade da EDENRED SOLUÇÕES DE PAGAMENTO, poderá ser acessado gratuitamente, a'
              'fim de trazer soluções para'
              'os portadores dos cartões pré-pagos virtuais, para que possam tomar decisões com mobilidade física e'
              'autonomia.'
              '\n3.2 Estarão disponíveis neste Site: a consulta de saldo, bloqueio e desbloqueio do cartão,'
              'extrato, status, alteração de senha'
              'e dados do portador e resgate de senha.'
              '\n3.3 Para utilização do Site, o usuário deverá realizar uma validação de dados, dispondo das'
              'seguintes informações:'
              '\n· Nome completo'
              '\n· CPF'
              '\n· Data de nascimento'
              '\n· Nome da mãe do portador'
              '\n3.4 O usuário se responsabiliza pela precisão e veracidade dos dados informados e reconhece que'
              'a inconsistência destes,'
              'poderá implicar na limitação no acesso ao Site.'
              '\n3.5 O usuário assume inteira responsabilidade pela guarda, sigilo e boa utilização do login e'
              'senha cadastrada, isentando a'
              'Edenred Soluções de Pagamento de qualquer responsabilidade.'
              '\n3.6 O login e senha só poderão ser utilizados pelo usuário cadastrado, sendo expressamente'
              'proibido o compartilhamento de'
              'login e/ou senha com quaisquer terceiros.'
              '\n\n4. PRIVACIDADE - INFORMAÇÕES DOS USUÁRIOS\n'
              '\n4.1. Existem 02 (duas) formas de coleta de informações dos Usuários (“Informações”): (i) emissão'
              'do cartão pelo Cliente no'
              'Portal de Pedidos e (ii) validação de dados preenchido pelo Usuário no Site.'
              '\n4.2. Assim, a EDENRED SOLUÇÕES DE PAGAMENTO coleta as seguintes Informações dos Usuários:'
              '\n(i) dados cadastrais: como nome, endereço, CPF, data de nascimento, gênero;'
              '\n((ii) dados de transações financeiras: número de cartão pré-pago, dados de compra de produtos,'
              'os valores transacionados em'
              'operações que utilizem os serviços da EDENRED SOLUÇÕES DE PAGAMENTO;'
              '\n(4.3. As Informações dos Usuários são coletadas, armazenadas, tratadas, processadas e utilizadas'
              'pela EDENRED SOLUÇÕES DE'
              'PAGAMENTO com as seguintes finalidades:'
              '\n(i) cumprir obrigações legais de manutenção de informações, regras do Banco Central do Brasil e'
              'outros regulamentos'
              'aplicáveis;'
              '\n(ii) integração de seus sistemas internos;'
              '\n(iii) viabilizar o processo de emissão de cartões pré-pagos;'
              '\n(iv) viabilizar acesso aos seus serviços oferecidos pelos cartões pré-pagos;'
              '\n(v) criar uma conta de acesso aos seus sistemas;'
              '\n(vi) confirmar a identidade de quem utiliza seus serviços;'
              '\n(vii) manter e atualizar periodicamente os dados pessoais da base cadastral de Usuários;'
              '\n(viii) encaminhar dúvidas ou requerimentos ao suporte;'
              '\n(ix) monitorar o atendimento;'
              '\n4.5. A EDENRED SOLUÇÕES DE PAGAMENTO, a fim de possibilitar a utilização de seus serviços,'
              'compartilha os dados de seus'
              'Usuários de acordo com as regulações da Circular n.º 3.461 do Banco Central do Brasil, que prevê o'
              'registro e compartilhamento de'
              'dados de cartões pré-pagos em determinados casos. Ainda, a EDENRED SOLUÇÕES DE PAGAMENTO compartilha'
              'dados com empresas'
              'processadoras. Ademais, os dados poderão ser compartilhados, se houver suspeita fundada de fraudes,'
              'no bojo da contratação de'
              'serviços antifraude específicos ou no âmbito de outras demandas legais, inclusive para eventual'
              'defesa dos direitos e interesses'
              'da EDENRED SOLUÇÕES DE PAGAMENTO em quaisquer tipos de conflitos, especialmente ações judiciais.'
              '\n4.6. A EDENRED SOLUÇÕES DE PAGAMENTO adota medidas de segurança para proteger seus sistemas e'
              'bases de dados, dentre elas:'
              'controles de acesso de informações, utilização de firewalls, análise de comportamentos que'
              'comprometam a segurança do Site e do'
              'usuário, de modo a identificar comportamentos fraudulentos que possam prejudicar o usuário e a'
              'EDENRED SOLUÇÕES DE PAGAMENTOS ; e'
              'implementação de política interna de segurança da informação.'
              '\n4.7. A EDENRED SOLUÇÕES DE PAGAMENTO assegura aos Usuários os direitos previstos na legislação'
              'de proteção de dados pessoais'
              'da seguinte maneira:'
              '\n(i) retenção de dados: a EDENRED SOLUÇÕES DE PAGAMENTO armazena os dados pessoais que coleta'
              'apenas pelo tempo necessário para'
              'atingir as finalidades para as quais foram coletados, observados eventuais prazos legais e'
              'necessidade de defesa da empresa em'
              'processos;'
              '\n(ii) acesso a dados: o Usuário pode requerer o acesso aos dados pessoais armazenados nos Sites,'
              'bem como informações sobre'
              'possível compartilhamento destes;'
              '\n(iii) correção: o Usuário pode realizar a alteração de dados no Site (telefone celular, e-mail e'
              'data de nascimento) e'
              'solicitar a correção ou atualização de dados pessoais incorretos junto à área de Recursos Humanos de'
              'sua empresa (exceto o número'
              'do CPF);'
              '\n(iv) portabilidade: o Usuário pode requerer a portabilidade de seus dados pessoais armazenados'
              'na plataforma, que será'
              'cumprido mediante a entrega pela EDENRED SOLUÇÕES DE PAGAMENTO da cópia dos dados pessoais em'
              'formato de leitura comum.'
              '\n(v) exclusão de dados: após o encerramento da prestação dos serviços, o Usuário poderá requerer'
              'a exclusão de seus dados'
              'pessoais. É possível que, mesmo após o requerimento de exclusão de conta na plataforma, alguns dados'
              'permaneçam armazenados,'
              'devido a obrigações legais da EDENRED SOLUÇÕES DE PAGAMENTO ou para proteção dos interesses legais'
              'da EDENRED SOLUÇÕES DE'
              'PAGAMENTO ou de seus clientes;'
              '\n\n6. RESPONSABILIDADES\n'
              '\n6.1. O Usuário não poderá praticar as seguintes ações com relação ao Site, no todo ou em parte,'
              'sem prejuízo de outras que'
              'sejam consideradas ilegais, contrariem a ordem pública ou atentem contra a moral e os bons costumes:'
              '\ni) prática de quaisquer atos ilícitos e/ou violação da legislação vigente, inclusive das'
              'disposições da Lei 9.613/98 e da Lei'
              '12.846/13;'
              '\nii) Utilizar o Site e/ou qualquer conteúdo dele constante, no todo ou em parte, sob qualquer'
              'meio ou forma, com propósito'
              'diverso daquele a que este se destina e de forma diversa da prevista neste TERMO, inclusive'
              'divulgando, a qualquer título, a'
              'terceiros que não tenham ou não devam ter acesso ao Site;'
              '\niii) Apagar, deturpar, corromper, alterar, editar, adaptar, transmitir ou de qualquer forma'
              'modificar, sob qualquer meio ou'
              'forma, no todo ou em parte, o Site, e/ou qualquer conteúdo dele constante;'
              '\niv) Fazer publicidade ou marketing associando sua imagem a EDENRED SOLUÇÕES DE PAGAMENTO, ou a'
              'qualquer empresa afiliada,'
              'controlada, coligada ou pertencente ao seu grupo econômico.'
              '\nv) Carregar, enviar e/ou transmitir qualquer conteúdo de cunho erótico, pornográfico, obsceno,'
              'difamatório ou calunioso ou que'
              'façam apologia ao crime, uso de drogas, consumo de bebidas alcoólicas ou de produtos fumígenos,'
              'violência física ou moral;'
              '\nvi) Carregar, enviar e/ou transmitir qualquer conteúdo que promova ou incite o preconceito'
              '(inclusive de origem, raça, sexo,'
              'cor, orientação sexual e idade) ou qualquer forma de discriminação, bem como o ódio ou atividades'
              'ilegais;'
              '\nvii) Ameaçar, coagir, ou causar constrangimento físico ou moral aos demais Usuários;'
              '\nviii) Realizar atos que causem ou propiciem a contaminação ou prejudiquem quaisquer equipamentos'
              'da EDENRED SOLUÇÕES DE'
              'PAGAMENTO, de suas empresas e/ou de terceiros, inclusive por meio de vírus, trojans, malware, worm,'
              'bot, backdoor, spyware,'
              'rootkit, ou por quaisquer outros dispositivos que venham a ser criados;'
              '\nviiii) Praticar quaisquer atos em relação ao Site, direta ou indiretamente, no todo ou em parte,'
              'que possam causar prejuízo à'
              'EDENRED SOLUÇÕES DE PAGAMENTO, a qualquer Usuário e/ou a quaisquer terceiros;'
              '\nix) Usar qualquer nome empresarial, marca, nome de domínio, slogan ou expressão de propaganda ou'
              'qualquer sinal distintivo ou'
              'bem de propriedade intelectual de titularidade da EDENRED SOLUÇÕES DE PAGAMENTO, ou de qualquer'
              'empresa ou marca afiliada,'
              'controlada, coligada ou pertencente ao seu grupo econômico.'
              '\n6.2. O Usuário é exclusivamente responsável:'
              '\ni) Por todos e quaisquer atos ou omissões por ele realizados no ambiente do Site;'
              '\nii) Pela reparação de todos e quaisquer danos, diretos ou indiretos, que sejam causados à'
              'EDENRED SOLUÇÕES DE PAGAMENTO, a'
              'qualquer outro Usuário, ou, ainda, a qualquer terceiro, inclusive em virtude do descumprimento do'
              'disposto neste TERMO. Sem'
              'prejuízo de outras medidas, a EDENRED SOLUÇÕES DE PAGAMENTO poderá, por si ou por terceiros, a'
              'qualquer tempo, a seu exclusivo'
              'critério, sem necessidade de qualquer aviso ou notificação prévia,'
              'suspender o acesso ao Site de qualquer Usuário, a qualquer tempo, caso este descumpra qualquer'
              'disposição deste TERMO e demais'
              'políticas do Site ou da legislação vigente aplicável.'
              '\niii) Pelo uso indevido de dados e/ou informações referentes ao conteúdo do site EDENRED SOLUÇÕES'
              'DE PAGAMENTO,'
              'responsabilizando-se por todos os prejuízos causados a EDENRED SOLUÇÕES DE PAGAMENTO ou a terceiros.'
              '\niv) Por todos e quaisquer atos ou omissões por ele realizado no ambiente do aplicativo.'
              '\nv) Realizar imediatamente o bloqueio ou cancelamento do cartão na ocorrência de furto, roubo,'
              'extravio, falsificação, dano,'
              'fraude ou suspeita de fraude do CARTÃO ou na sua utilização, responsabilizando-se pelos gastos'
              'efetuados com o CARTÃO até o'
              'momento da comunicação da respectiva ocorrência.'
              '\n6.3. Em nenhuma hipótese, a EDENRED SOLUÇÕES DE PAGAMENTO será responsável:'
              '\ni) Pelo pagamento de custos ou danos, inclusive danos diretos, indiretos, específicos,'
              'acidentais ou emergentes, decorrentes'
              'do acesso ou uso, impossibilidade de acesso ou uso deste Site ou de alguma de suas funções ou'
              'partes, inclusive com o fim de'
              'consultar ou baixar informações, dados, textos, imagens ou outros materiais acessíveis por meio'
              'deste Site;'
              '\nii) Por qualquer ato ou omissão realizado e/ou dano causado pelo Usuário neste Site;'
              '\niii) Pela instalação no equipamento do Usuário ou de terceiros, de vírus, trojans, malware,'
              'worm, bot, backdoor, spyware,'
              'rootkit, ou de quaisquer outros dispositivos que venham a ser criados, em decorrência da navegação'
              'na Internet pelo Usuário.'
              '\niv) Pelo uso indevido por qualquer usuário ou terceiros do Site, no todo ou em parte, por'
              'qualquer meio ou forma, incluindo,'
              'mas não se limitando à reprodução e/ou divulgação em quaisquer meios;'
              '\nv) Pela suspensão, interrupção ou remoção do Site.'
              '\nvi) Por qualquer dano direto, indireto, acidental, excepcional ou resultante do uso ou inaptidão'
              'do desfrute dos seus'
              'serviços, ou pelo custo da aquisição de serviços substitutos.'
              '\n6.4 O Usuário se declara ciente que a EDENRED SOLUÇÕES DE PAGAMENTO não controla os conteúdos ou'
              'produtos transmitidos,'
              'difundidos ou disponibilizados a terceiros pelo estabelecimento no uso das funcionalidades, bem'
              'como, que a EDENRED SOLUÇÕES DE'
              'PAGAMENTO não é a proprietária dos produtos ou responsável pela qualidade dos produtos e serviços'
              'ofertados, e que não intervém na'
              'entrega dos produtos ou na prestação dos serviços, fica certo desde já, que o estabelecimento é o'
              'único e exclusivo responsável'
              'pelo conteúdo da oferta disponibilizada, respondendo integralmente pelos eventuais danos que tenha'
              'dado causa, inclusive por ação'
              'e/ou omissão.'
              '\n6.5 Fica certo desde já que a EDENRED SOLUÇÕES DE PAGAMENTO não será responsabilizada pelo não'
              'funcionamento do site'
              'decorrente de falha ou interrupção de qualquer serviço de telecomunicação, conexão à internet,'
              'provedor de acesso à internet ou de'
              'qualquer outro provedor de comunicações, caso fortuito, força maior ou de qualquer outra falha ou'
              'problema não atribuíveis à'
              'EDENRED SOLUÇÕES DE PAGAMENTO;'
              '\n\n7. PROPRIEDADE INTELECTUAL\n'
              '\n7.1. Pertencem à EDENRED SOLUÇÕES DE PAGAMENTO todos e quaisquer direitos intelectuais sobre o'
              'Site, incluindo, mas não se'
              'limitando a:'
              '\nI) Todo e qualquer software, aplicativo ou funcionalidade empregado pela EDENRED SOLUÇÕES DE'
              'PAGAMENTO para manter e melhorar'
              'o funcionamento do Site;'
              '\nII) Identidade visual do Site; e'
              '\nIII)Todo e qualquer conteúdo criado e produzido exclusivamente pela EDENRED SOLUÇÕES DE'
              'PAGAMENTO por si ou por terceiros.'
              '\n\n8. DISPOSIÇÕES GERAIS.\n'
              '\n8.2 A tolerância quanto ao eventual descumprimento de quaisquer das disposições deste TERMO'
              'deste Site por qualquer Usuário'
              'não constituirá renúncia ao direito de exigir o cumprimento da obrigação.'
              '\n8.3 A EDENRED SOLUÇÕES DE PAGAMENTO poderá, a qualquer tempo, a seu exclusivo critério e sem'
              'necessidade de qualquer aviso'
              'prévio:'
              '\n(i) Tirar o Site do ar;'
              '\n(ii) Alterar e/ou atualizar no todo ou em parte este TERMO;'
              '\n(iii) Alterar e/ou atualizar as políticas comerciais presentes no Site.'
              '\n8.5. A EDENRED SOLUÇÕES DE PAGAMENTO reserva a si o direito de reexaminar e corrigir os termos e'
              'condições desse acordo a'
              'qualquer momento. Qualquer correção será obrigatória e válida imediatamente após a postagem do'
              'acordo modificado em nosso Site.'
              'Caso a atualização/correção implique em alteração sensível quanto ao tratamento dos dados pessoais'
              'dos Usuários, a EDENRED'
              'SOLUÇÕES DE PAGAMENTO envidará os melhores esforços para providenciar a devida comunicação aos'
              'Usuários, bem como possibilitar a'
              'revogação do consentimento anteriormente dado, se o caso.'
              '\n8.6. Os comunicados, newsletters, avisos de ofertas e mensagens publicitárias enviadas por'
              'e-mail trarão, obrigatoriamente,'
              'opção de cancelamento (opt-out) do envio daquele tipo de mensagem por parte do Site. O cancelamento'
              'do envio também pode ser'
              'solicitado pelos canais de atendimento disponíveis da EDENRED SOLUÇÕES DE PAGAMENTO.'
              '\n8.7. O processo de cancelamento de envio é vinculado ao e-mail do Usuário. Portanto Usuários que'
              'possuam mais de um e-mail'
              'cadastrado poderão continuar a receber os comunicados ou as mensagens publicitárias no e-mail que'
              'não foi descadastrado.'
              '\n8.8. A empresa contratada não armazena nem utiliza de nenhuma forma os e-mails de cadastro da'
              'EDENRED SOLUÇÕES DE PAGAMENTO'
              'com para qualquer outro fim que não o envio das mensagens, de acordo com as preferências de cada'
              'Usuário e as disposições'
              'previstas na presente Política de Privacidade e nos Termos e Condições de Uso da EDENRED SOLUÇÕES DE'
              'PAGAMENTO.'
              '\n8.9. As marcas registradas, nomes, logotipos e marcas de serviços mostrados são legalmente,'
              'reconhecidos ou não, do'
              'proprietário. Nada contido nesse site deve ser entendido como uma forma de conceder licença ou'
              'direito de usar qualquer marca'
              'registrada sem a autorização prévia escrita do dono. O conteúdo textual apresentado nesse site é'
              'propriedade de seu respectivo'
              'autor e não pode ser reproduzido total ou parcialmente sem sua expressa permissão escrita.'
              '\n8.10. O Usuário está ciente da coleta, armazenamento, tratamento, processamento e uso das                              '
              'Informações enviadas e/ou'
              'transmitidas pelo Usuário nos termos aqui estabelecidos.'
              '\n8.11. A EDENRED SOLUÇÕES DE PAGAMENTO poderá divulgar notificações ou mensagens através do Site'
              'para informar os Usuários a'
              'respeito de mudanças nos serviços ou no Termo de Uso, Navegação, Política, Privacidade e'
              'Compartilhamento, ou outros assuntos'
              'relevantes.'
              '\nEste TERMO é regido de acordo com a legislação brasileira. Quaisquer disputas ou controvérsias'
              'oriundas de quaisquer atos'
              'praticados no âmbito do Sites pelos Usuários, inclusive com relação ao descumprimento deste TERMO,'
              'e/ou demais políticas do Site,'
              'serão processadas na Comarca da Capital do Estado de São Paulo.\n\n\n'
              '"DECLARO QUE LI E ESTOU CIENTE DAS CONDIÇÕES DO TERMO DE USO APRESENTADO"',
              style: TextStyle(fontSize: 20),
            ),
          )),
    );
  }
}
